name = "bedrock-live-map"
main = "src/worker.js"
compatibility_date = "2026-01-01"

[[durable_objects.bindings]]
name = "WORLD_MAP"
class_name = "WorldMapState"

[[migrations]]
tag = "v1"
new_classes = ["WorldMapState"]
